name:
  type: str
  help: What is the name of the microservice?
version:
  type: str
  help: What is the version of the microservice?
project_name:
  type: str
  help: What is the name of the project?
kubernetes_config:
  type: str
  default: microservice-config
  help: What is the kubernetes config?
kubernetes_registry:
  type: str
  default: "localhost:5000"
  help: What is the kubernetes registry?

_envops:
  block_start_string: "{%"
  block_end_string: "%}"
  comment_start_string: "{#"
  comment_end_string: "#}"
  variable_start_string: "{{"
  variable_end_string: "}}"
  keep_trailing_newline: false

_templates_suffix: .jinja

_tasks:
  - make -s deploy
