_envops:
  block_start_string: "{%"
  block_end_string: "%}"
  comment_start_string: "{#"
  comment_end_string: "#}"
  variable_start_string: "{{"
  variable_end_string: "}}"
  keep_trailing_newline: false

_templates_suffix: .jinja

_exclude:
  - "copier.yml"
  - "_utils.py"

_functions:
  - "_utils.build_docker_compose"
