name: Publish Templates

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build Microservice Initi Template
        run: tar -czvf microservice-init.tar.gz -C ${{ github.workspace }}/microservice/init .

      - name: Build Microservice Python Init Template
        run: tar -czvf microservice-python-init.tar.gz -C ${{ github.workspace }}/microservice/language/python/init .

      - name: Build Microservice Python Package Manager Poetry Template
        run: tar -czvf microservice-python-package-manager-poetry.tar.gz -C ${{ github.workspace }}/microservice/language/python/package-manager/poetry .

      - name: Build Microservice Python Package Manager Pip Template
        run: tar -czvf microservice-python-package-manager-pip.tar.gz -C ${{ github.workspace }}/microservice/language/python/package-manager/pip .

      - name: Build Microservice Python Deploy Docker Template
        run: tar -czvf microservice-python-deploy-docker.tar.gz -C ${{ github.workspace }}/microservice/language/python/deploy/docker .

      - name: Build Microservice Python Deploy Kubernetes Template
        run: tar -czvf microservice-python-deploy-kubernetes.tar.gz -C ${{ github.workspace }}/microservice/language/python/deploy/kubernetes .

      - name: Build Project Init Template
        run: tar -czvf project-init.tar.gz -C ${{ github.workspace }}/project/init .

      - name: Build Project API Gateway Minos Init Template
        run: tar -czvf project-api-gateway-minos-init.tar.gz -C ${{ github.workspace }}/project/api-gateway/minos/init .

      - name: Build Project API Gateway Minos Deploy Docker Compose Template
        run: tar -czvf project-api-gateway-minos-deploy-docker-compose.tar.gz -C ${{ github.workspace }}/project/api-gateway/minos/deploy/docker-compose .

      - name: Build Project API Gateway Minos Deploy Kubernetes Template
        run: tar -czvf project-api-gateway-minos-deploy-kubernetes.tar.gz -C ${{ github.workspace }}/project/api-gateway/minos/deploy/kubernetes .

      - name: Build Project API Gateway Minos Deploy Remote Template
        run: tar -czvf project-api-gateway-minos-deploy-remote.tar.gz -C ${{ github.workspace }}/project/api-gateway/minos/deploy/remote .

      - name: Build Project Broker Kafka Init Template
        run: tar -czvf project-broker-kafka-init.tar.gz -C ${{ github.workspace }}/project/broker/kafka/init .

      - name: Build Project Broker Kafka Deploy Docker Compose Template
        run: tar -czvf project-broker-kafka-deploy-docker-compose.tar.gz -C ${{ github.workspace }}/project/broker/kafka/deploy/docker-compose .

      - name: Build Project Broker Kafka Deploy Kubernetes Template
        run: tar -czvf project-broker-kafka-deploy-kubernetes.tar.gz -C ${{ github.workspace }}/project/broker/kafka/deploy/kubernetes .

      - name: Build Project Broker Kafka Deploy Remote Template
        run: tar -czvf project-broker-kafka-deploy-remote.tar.gz -C ${{ github.workspace }}/project/broker/kafka/deploy/remote .

      - name: Build Project Database Postgres Init Template
        run: tar -czvf project-database-postgres-init.tar.gz -C ${{ github.workspace }}/project/database/postgres/init .

      - name: Build Project Database Postgres Deploy Docker Compose Template
        run: tar -czvf project-database-postgres-deploy-docker-compose.tar.gz -C ${{ github.workspace }}/project/database/postgres/deploy/docker-compose .

      - name: Build Project Database Postgres Deploy Kubernetes Template
        run: tar -czvf project-database-postgres-deploy-kubernetes.tar.gz -C ${{ github.workspace }}/project/database/postgres/deploy/kubernetes .

      - name: Build Project Database Postgres Deploy Remote Template
        run: tar -czvf project-database-postgres-deploy-remote.tar.gz -C ${{ github.workspace }}/project/database/postgres/deploy/remote .

      - name: Build Project Database Redis Init Template
        run: tar -czvf project-database-redis-init.tar.gz -C ${{ github.workspace }}/project/database/redis/init .

      - name: Build Project Database Redis Deploy Docker Compose Template
        run: tar -czvf project-database-redis-deploy-docker-compose.tar.gz -C ${{ github.workspace }}/project/database/redis/deploy/docker-compose .

      - name: Build Project Database Redis Deploy Kubernetes Template
        run: tar -czvf project-database-redis-deploy-kubernetes.tar.gz -C ${{ github.workspace }}/project/database/redis/deploy/kubernetes .

      - name: Build Project Database Redis Deploy Remote Template
        run: tar -czvf project-database-redis-deploy-remote.tar.gz -C ${{ github.workspace }}/project/database/redis/deploy/remote .

      - name: Build Project Deploy Docker Compose Template
        run: tar -czvf project-deploy-docker-compose.tar.gz -C ${{ github.workspace }}/project/deploy/docker-compose .

      - name: Build Project Discovery Minos Init Template
        run: tar -czvf project-discovery-minos-init.tar.gz -C ${{ github.workspace }}/project/discovery/minos/init .
        
      - name: Build Project Discovery Minos Deploy Docker Compose Template
        run: tar -czvf project-discovery-minos-deploy-docker-compose.tar.gz -C ${{ github.workspace }}/project/discovery/minos/deploy/docker-compose .

      - name: Build Project Discovery Minos Deploy Kubernetes Template
        run: tar -czvf project-discovery-minos-deploy-kubernetes.tar.gz -C ${{ github.workspace }}/project/discovery/minos/deploy/kubernetes .

      - name: Build Project Discovery Minos Deploy Remote Template
        run: tar -czvf project-discovery-minos-deploy-remote.tar.gz -C ${{ github.workspace }}/project/discovery/minos/deploy/remote .

      - name: Build Project Deploy Docker Compose Template
        run: tar -czvf project-deploy-docker-compose.tar.gz -C ${{ github.workspace }}/project/deploy/docker-compose .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            microservice-init.tar.gz
            microservice-python-init.tar.gz
            microservice-python-package-manager-poetry.tar.gz
            microservice-python-package-manager-pip.tar.gz
            microservice-python-deploy-docker.tar.gz
            microservice-python-deploy-kubernetes.tar.gz
            project-init.tar.gz
            project-api-gateway-minos-init.tar.gz
            project-api-gateway-minos-deploy-docker-compose.tar.gz
            project-api-gateway-minos-deploy-kubernetes.tar.gz
            project-api-gateway-minos-deploy-remote.tar.gz
            project-broker-kafka-init.tar.gz
            project-broker-kafka-deploy-docker-compose.tar.gz
            project-broker-kafka-deploy-kubernetes.tar.gz
            project-broker-kafka-deploy-remote.tar.gz
            project-database-postgres-init.tar.gz
            project-database-postgres-deploy-docker-compose.tar.gz
            project-database-postgres-deploy-kubernetes.tar.gz
            project-database-postgres-deploy-remote.tar.gz
            project-database-redis-init.tar.gz
            project-database-redis-deploy-docker-compose.tar.gz
            project-database-redis-deploy-kubernetes.tar.gz
            project-database-redis-deploy-remote.tar.gz
            project-deploy-docker-compose.tar.gz
            project-discovery-minos-init.tar.gz
            project-discovery-minos-deploy-docker-compose.tar.gz
            project-discovery-minos-deploy-kubernetes.tar.gz
            project-discovery-minos-deploy-remote.tar.gz

