name: Publish Templates

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build Templates
        run: sh ${{ github.workspace }}/build.sh

      - name: Release Templates
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          fail_on_unmatched_files: true
          files: ${{ github.workspace }}/.build/*