name: Publish Templates

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Upload Microservice Init Template
        uses: actions/upload-artifact@v2
        with:
            name: microservice-init
            path: ${{ github.workspace }}/microservice

      - name: Upload Project Initialize Template
        uses: actions/upload-artifact@v2
        with:
            name: project-init
            path: ${{ github.workspace }}/project
