name: Publish Templates

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Build Microservice Init Template
        run: tar -czvf microservice-init.tar.gz -C ${{ github.workspace }}/microservice .

      - name: Build Project Init Template
        run: tar -czvf project-init.tar.gz -C ${{ github.workspace }}/project .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            microservice-init.tar.gz
            project-init.tar.gz

